# SPDX-FileCopyrightText: 2022 nerdyscout <https://github.com/nerdyscout/>
#
# SPDX-License-Identifier: CC0-1.0

name: KiBot

on:
  workflow_dispatch:
  push:
    paths:
    - "sources/*.kicad_sch"
    - "sources/*.kicad_pcb"
    - "sources/*.kicad_pro"
    - "**/*kibot.yml"
  pull_request:
    paths:
    - "sources/*.kicad_sch"
    - "sources/*.kicad_pcb"
    - "sources/*.kicad_pro"
    - "**/*kibot.yml"

env:
  schema: "eps-re_project.kicad_sch"
  board: "*.kicad_pcb"
  dir: .
  config: ../kibot.yml

defaults:
  run:
    working-directory: ./sources

jobs:
# checks
  ERC:
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki8
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_drc -v -i
  DRC:
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki8
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc -v -i
# documentation
  docs:
    runs-on: ubuntu-latest
    needs: [ERC]
    container:
      image: setsoft/kicad_auto:ki8
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            ibom.html octopart.csv schematic.pdf schematic.svg board_top.pdf board_bottom.pdf
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_docs
          if-no-files-found: error
          path: |
            sources/docs/**
            !sources/**/*.ogv
            !sources/**/*.log
# fabrications
  gerbers:
    runs-on: ubuntu-latest
    needs: [DRC]
    container:
      image: setsoft/kicad_auto:ki8
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: |
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            gerbers.gbr drills.gbr drills.drl pickandplace.csv bom.csv
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_gerbers
          if-no-files-found: error
          path: |
            sources/gerbers/**
            !sources/**/*.ogv
            !sources/**/*.log
# cad
  cad:
    runs-on: ubuntu-latest
    needs: [DRC]
    container:
      image: setsoft/kicad_auto:ki8
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            model.step openboardview.brd autocad.dxf
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_cad
          if-no-files-found: error
          path: |
            sources/cad/**
            !sources/**/*.ogv
            !sources/**/*.log
# images
#  render:
#    runs-on: ubuntu-latest
#    needs: [DRC]
#    container:
#      image: setsoft/kicad_auto:ki8
#    steps:
#      - uses: actions/checkout@v3
#      - name: run kibot
#        run: | 
#          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
#            board_black_top.svg board_black_bottom.svg
#      - uses: actions/upload-artifact@v3.1.1
#        if: ${{success()}}
#        with:
#          name: ${{github.event.repository.name}}_img
#          if-no-files-found: error
#          path: |
#            sources/img/**
#            !sources/**/*.ogv
#            !sources/**/*.log
